const baseInput =
  "w-full px-4 py-3 rounded-xl text-sm focus:outline-none transition-colors";

export const themes = {
  v1: {
    shell: "h-full bg-gray-950 text-white",
    topNav: "flex items-center h-14 bg-gray-950 border-b border-gray-800/80 px-6 shrink-0",
    logoBox: "w-7 h-7 rounded-lg bg-red-700/20 border border-red-600/30 flex items-center justify-center shrink-0",
    logoIcon: "w-4 h-4 text-red-400",
    brand: "text-xs font-bold text-gray-600 tracking-wide uppercase hidden xl:block",
    navBtn: (active) =>
      `px-3 py-2 rounded-lg text-sm font-medium transition-colors whitespace-nowrap ${active ? "bg-blue-600/15 text-blue-400" : "text-gray-500 hover:text-gray-200 hover:bg-gray-800/60"}`,
    toggleBtn: "flex items-center justify-center w-8 h-8 rounded-lg text-amber-400 hover:text-amber-300 hover:bg-gray-800/60 transition-colors",
    avatarBox: "w-7 h-7 rounded-full bg-blue-600/20 border border-blue-500/30 flex items-center justify-center",
    avatarInitials: "text-[11px] font-bold text-blue-400",
    userName: "text-sm text-gray-400 hidden xl:block",
    userNameShort: "text-sm text-gray-400 xl:hidden",
    avatarBtn: "flex items-center justify-center w-7 h-7 rounded-full bg-blue-600/20 border border-blue-500/30 hover:bg-blue-600/30 transition-colors",
    userMenu: "absolute right-0 top-full mt-2 w-56 rounded-xl border border-gray-800 bg-gray-900 shadow-xl z-50 p-2",
    menuLabel: "text-[10px] text-gray-600 uppercase tracking-widest font-semibold",
    menuName: "text-sm font-semibold text-white",
    menuEmail: "text-xs text-gray-500 font-mono",
    menuDivider: "my-2 border-t border-gray-800",
    logoutBtn: "flex items-center gap-2 w-full px-3 py-2 text-left rounded-lg text-sm font-medium text-red-400 hover:bg-red-500/10 hover:text-red-300 transition-colors",
    logoutIcon: "w-4 h-4",
    bottomBar: "lg:hidden fixed bottom-0 left-0 right-0 z-50 bg-gray-900/95 backdrop-blur-sm border-t border-gray-800",
    bottomTab: (active) =>
      `flex-1 flex flex-col items-center gap-1 py-1.5 rounded-xl transition-colors ${active ? "text-blue-400" : "text-gray-600 hover:text-gray-400"}`,
    backBtn: "flex items-center justify-center w-9 h-9 rounded-full bg-gray-800 hover:bg-gray-700 transition-colors shrink-0",
    backIcon: "w-4 h-4 text-gray-300",
    h1: "text-xl font-bold text-white lg:text-2xl",
    subtitle: "text-xs text-gray-500 mt-0.5",
    pageWrap: "px-4 pb-6 lg:px-8",
    card: "bg-gray-900 border border-gray-800 rounded-2xl",
    cardBorder: "border-b border-gray-800",
    cardTitle: "text-sm font-semibold text-gray-200",
    cardMeta: "text-xs text-gray-600 font-mono",
    divide: "divide-y divide-gray-800/60",
    rowBtn: "w-full flex items-center gap-3 px-4 py-3.5 hover:bg-gray-800/50 active:bg-gray-800 transition-colors text-left group",
    vehCode: "font-mono text-sm font-bold text-white",
    vehCodeLg: "font-mono text-4xl font-bold text-white leading-none",
    dot: "text-gray-700 text-xs",
    vehType: "text-sm text-gray-300 truncate",
    vehSub: "text-xs text-gray-600 mt-0.5 font-mono truncate",
    chevron: "w-4 h-4 text-gray-700 shrink-0 group-hover:text-gray-500 transition-colors",
    dashDate: "font-mono text-sm text-gray-600 mt-0.5",
    pill: "bg-gray-900 border border-gray-800",
    detailBrand: "text-gray-400 text-sm mt-1.5",
    infoTile: "bg-gray-800/60 rounded-xl px-3 py-2.5",
    infoTileLabel: "text-[10px] text-gray-600 uppercase tracking-wide font-semibold mb-1",
    infoTileValue: "font-mono text-sm font-medium text-gray-200",
    reportFaultBtn: "flex items-center justify-center gap-2 py-3.5 rounded-xl border border-red-600/40 text-red-400 hover:bg-red-500/10 active:bg-red-500/15 transition-colors font-semibold text-sm",
    registerBtn: "flex items-center justify-center gap-2 py-3.5 rounded-xl bg-blue-600 hover:bg-blue-500 active:bg-blue-700 text-white transition-colors font-semibold text-sm",
    histChip: (type) =>
      `text-xs px-2 py-0.5 rounded-full font-medium ${type === "preventiva" ? "bg-blue-500/10 text-blue-400" : "bg-orange-500/10 text-orange-400"}`,
    histDate: "font-mono text-xs text-gray-500",
    histCost: "font-mono text-sm font-bold text-white",
    histDesc: "text-sm text-gray-400 leading-relaxed",
    histFooter: "text-xs text-gray-700 mt-2 font-mono",
    label: "block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2",
    fieldBox: "flex items-center gap-3 px-4 py-3 bg-gray-900 border border-gray-800 rounded-xl",
    input: `${baseInput} bg-gray-900 border border-gray-800 text-white placeholder-gray-600 focus:border-blue-500`,
    textarea: `${baseInput} bg-gray-900 border border-gray-800 text-white placeholder-gray-600 focus:border-red-600/50 resize-none`,
    select: "flex-1 px-4 py-2.5 bg-gray-900 border border-gray-800 rounded-xl text-white text-sm focus:outline-none focus:border-blue-500 transition-colors",
    loginBtn: "w-full py-3.5 bg-red-700 hover:bg-red-600 active:bg-red-800 text-white font-bold rounded-xl transition-colors text-sm mt-1 shadow-lg shadow-red-950/40",
    submitReportBtn: "w-full py-4 bg-red-700 hover:bg-red-600 active:bg-red-800 text-white font-bold rounded-xl transition-colors text-sm shadow-lg shadow-red-950/40",
    saveMaintBtn: "w-full py-4 bg-blue-600 hover:bg-blue-500 active:bg-blue-700 text-white font-bold rounded-xl transition-colors text-sm mt-2",
    backDashBtn: "w-full py-3.5 bg-blue-600 hover:bg-blue-500 text-white font-bold rounded-xl transition-colors text-sm",
    smallBtn: "flex items-center gap-2 px-4 py-2.5 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-sm font-medium transition-colors",
    cancelBtn: "px-5 py-3 bg-gray-800 hover:bg-gray-700 text-gray-400 rounded-xl text-sm transition-colors",
    saveUserBtn: "flex-1 py-3 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-sm font-semibold transition-colors",
    typeBtn: (active) =>
      `py-3 rounded-xl border font-semibold text-sm capitalize transition-colors ${active ? "bg-blue-600/15 border-blue-500 text-blue-300" : "border-gray-800 text-gray-500 hover:border-gray-700 hover:text-gray-400"}`,
    urgBtn: (urgency, active) => {
      const map = {
        alta: { active: "border-red-500 bg-red-500/10 text-red-300", inactive: "border-red-900/60 text-red-600" },
        media: { active: "border-amber-500 bg-amber-500/10 text-amber-300", inactive: "border-amber-900/60 text-amber-600" },
        baja: { active: "border-blue-500 bg-blue-500/10 text-blue-300", inactive: "border-blue-900/60 text-blue-600" },
      };
      return `py-3 rounded-xl border font-bold text-sm capitalize transition-colors ${active ? map[urgency].active : map[urgency].inactive}`;
    },
    photoBtn: (active) =>
      `${active ? "bg-blue-500/10 border-blue-500/40 text-blue-400" : "border-gray-800 text-gray-500 hover:border-gray-700 hover:text-gray-400"} flex items-center gap-3 w-full px-4 py-3.5 rounded-xl border text-sm font-medium transition-colors`,
    photoIcon: "",
    checkIcon: "w-4 h-4 text-blue-400",
    confirmCircle: "bg-emerald-500/10 border border-emerald-500/20",
    confirmCheck: "w-12 h-12 text-emerald-400",
    confirmTitle: "text-2xl font-bold text-white mb-3",
    confirmText: "text-gray-400 text-sm",
    summaryCard: "bg-gray-900 border border-gray-800 rounded-xl p-4",
    summaryLabel: "text-[10px] text-gray-700 uppercase tracking-widest font-semibold mb-3",
    summaryCode: "font-mono text-sm font-bold text-white",
    summaryType: "text-xs text-gray-500",
    summarySub: "text-xs text-gray-600 mt-0.5 font-mono",
    alertIconBox: (status) =>
      `w-10 h-10 rounded-xl flex items-center justify-center shrink-0 ${status === "critical" ? "bg-red-500/10" : "bg-amber-500/10"}`,
    alertIcon: (status) => `w-5 h-5 ${status === "critical" ? "text-red-400" : "text-amber-400"}`,
    alertSub: (status) => `text-xs mt-0.5 font-medium font-mono ${status === "critical" ? "text-red-400" : "text-amber-400"}`,
    emptyCircle: "bg-emerald-500/10 border border-emerald-500/20",
    emptyCheck: "w-8 h-8 text-emerald-400",
    emptyTitle: "text-gray-400 font-medium",
    emptySub: "text-gray-600 text-sm mt-1",
    totalLabel: "text-[10px] text-gray-600 uppercase tracking-widest font-semibold",
    totalValue: "font-mono text-3xl font-bold text-white mt-1",
    totalSub: "text-xs text-gray-600 mt-1.5 font-mono",
    chartTitle: "text-sm font-semibold text-gray-300 mb-4",
    detCode: "font-mono text-sm font-bold text-white w-14 shrink-0",
    detTrack: "h-1.5 bg-gray-800 rounded-full overflow-hidden",
    detFill: "h-full bg-blue-500/60 rounded-full",
    detCost: "font-mono text-sm text-gray-300 w-28 text-right shrink-0",
    addForm: "bg-gray-900 border border-blue-500/20 rounded-2xl p-5 space-y-3",
    formTitle: "text-sm font-semibold text-white",
    userAvatar: "w-9 h-9 rounded-full bg-gray-800 border border-gray-700/80 flex items-center justify-center shrink-0",
    userAvatarTxt: "text-xs font-bold text-gray-300",
    userName: "text-sm font-semibold text-white truncate",
    userEmail: "text-xs text-gray-600 truncate font-mono",
    roleBadge: (role) =>
      `text-xs px-2.5 py-1 rounded-full font-medium shrink-0 ${
        role === "Administrador" ? "bg-purple-500/10 text-purple-400" :
        role === "Inspector de Material Mayor" ? "bg-blue-500/10 text-blue-400" :
        role === "Teniente Tercero" ? "bg-amber-500/10 text-amber-400" :
        "bg-gray-800 text-gray-500"
      }`,
    loginOuter: "relative min-h-full bg-gray-950 flex flex-col items-center justify-center p-6",
    loginGlow: "absolute inset-0 bg-[radial-gradient(ellipse_80%_60%_at_50%_-5%,rgba(153,27,27,0.15),transparent)] pointer-events-none",
    loginLogoBox: "w-20 h-20 rounded-2xl bg-red-700/20 border border-red-600/25 flex items-center justify-center mb-5 shadow-2xl shadow-red-950/50",
    loginLogoIcon: "w-11 h-11 text-red-400",
    loginBrand1: "text-xs font-bold text-red-400 tracking-widest uppercase",
    loginBrand2: "text-xs text-gray-600 tracking-widest uppercase mt-0.5",
    loginTitle: "text-2xl font-bold text-white text-center mt-5 leading-snug",
    loginSub: "text-sm text-gray-500 mt-1",
    loginCard: "bg-gray-900 border border-gray-800 rounded-2xl p-6 space-y-4",
    loginFooter: "text-center text-xs text-gray-700 mt-6",
    note: "text-xs text-gray-700 text-center",
    bloginFooterLabel: "Acceso restringido · 1ª Cía. CBM",
    chart: {
      grid: "#1f2937",
      axis: "#4b5563",
      bar: "#1d4ed8",
      barTop: "#3b82f6",
      barLabel: "#60a5fa",
      code: "#6b7280",
      barOpacity: 0.55,
    },
  },

  v2: {
    shell: "h-full bg-gray-50 text-gray-900",
    topNav: "flex items-center h-14 bg-white border-b border-gray-100 px-6 shrink-0 shadow-sm",
    logoBox: "w-7 h-7 rounded-lg bg-gray-900 flex items-center justify-center shrink-0",
    logoIcon: "w-4 h-4 text-white",
    brand: "text-xs font-medium text-gray-400 hidden xl:block",
    navBtn: (active) =>
      `px-3 py-2 rounded-lg text-sm font-medium transition-colors whitespace-nowrap ${active ? "bg-gray-100 text-gray-900" : "text-gray-500 hover:text-gray-800 hover:bg-gray-50"}`,
    toggleBtn: "flex items-center justify-center w-8 h-8 rounded-lg text-gray-500 hover:text-gray-800 hover:bg-gray-50 transition-colors",
    avatarBox: "w-7 h-7 rounded-full bg-gray-200 flex items-center justify-center",
    avatarInitials: "text-[11px] font-bold text-gray-600",
    userName: "text-sm text-gray-600 hidden xl:block",
    userNameShort: "text-sm text-gray-600 xl:hidden",
    avatarBtn: "flex items-center justify-center w-7 h-7 rounded-full bg-gray-200 hover:bg-gray-300 transition-colors",
    userMenu: "absolute right-0 top-full mt-2 w-56 rounded-xl border border-gray-100 bg-white shadow-lg z-50 p-2",
    menuLabel: "text-xs text-gray-400 uppercase tracking-wide font-medium",
    menuName: "text-sm font-semibold text-gray-900",
    menuEmail: "text-xs text-gray-400 font-mono",
    menuDivider: "my-2 border-t border-gray-100",
    logoutBtn: "flex items-center gap-2 w-full px-3 py-2 text-left rounded-lg text-sm font-medium text-red-600 hover:bg-gray-50 transition-colors",
    logoutIcon: "w-4 h-4",
    bottomBar: "lg:hidden fixed bottom-0 left-0 right-0 z-50 bg-white border-t border-gray-100",
    bottomTab: (active) =>
      `flex-1 flex flex-col items-center gap-1 py-1.5 rounded-xl transition-colors ${active ? "text-gray-900" : "text-gray-400 hover:text-gray-600"}`,
    backBtn: "flex items-center justify-center w-9 h-9 rounded-full bg-gray-100 hover:bg-gray-200 transition-colors shrink-0",
    backIcon: "w-4 h-4 text-gray-600",
    h1: "text-xl font-bold text-gray-900",
    subtitle: "text-xs text-gray-400 mt-0.5",
    pageWrap: "px-4 pb-6 lg:px-8",
    card: "bg-white rounded-2xl border border-gray-100 shadow-sm",
    cardBorder: "border-b border-gray-100",
    cardTitle: "text-sm font-semibold text-gray-900",
    cardMeta: "text-xs text-gray-400",
    divide: "divide-y divide-gray-100",
    rowBtn: "w-full flex items-center gap-3 px-4 py-4 hover:bg-gray-50 active:bg-gray-100 transition-colors text-left group",
    vehCode: "text-sm font-bold text-gray-900",
    vehCodeLg: "text-3xl font-bold text-gray-900 leading-none",
    dot: "text-gray-300 text-xs",
    vehType: "text-sm text-gray-600 truncate",
    vehSub: "text-xs text-gray-400 mt-0.5 truncate",
    chevron: "w-4 h-4 text-gray-300 shrink-0 group-hover:text-gray-500 transition-colors",
    dashDate: "text-sm text-gray-400 mt-0.5",
    pill: "bg-white border border-gray-200",
    detailBrand: "text-sm text-gray-500 mt-1",
    infoTile: "bg-gray-50 rounded-xl px-3 py-2.5",
    infoTileLabel: "text-xs text-gray-400 mb-0.5",
    infoTileValue: "text-sm font-semibold text-gray-900",
    reportFaultBtn: "py-3.5 rounded-xl border border-gray-200 text-gray-700 hover:bg-gray-50 active:bg-gray-100 transition-colors font-semibold text-sm",
    registerBtn: "py-3.5 rounded-xl bg-gray-900 hover:bg-gray-800 text-white transition-colors font-semibold text-sm",
    histChip: (type) =>
      `text-xs px-2 py-0.5 rounded-full font-medium ${type === "preventiva" ? "bg-blue-50 text-blue-700" : "bg-orange-50 text-orange-700"}`,
    histDate: "text-xs text-gray-400",
    histCost: "text-sm font-bold text-gray-900",
    histDesc: "text-sm text-gray-600 leading-relaxed",
    histFooter: "text-xs text-gray-400 mt-1.5",
    label: "text-xs font-medium text-gray-500 mb-2",
    fieldBox: "flex items-center gap-3 px-4 py-3 bg-white border border-gray-200 rounded-xl",
    input: `${baseInput} bg-white border border-gray-200 text-gray-900 placeholder-gray-400 focus:border-gray-400`,
    textarea: `${baseInput} bg-white border border-gray-200 text-gray-900 placeholder-gray-400 focus:border-gray-400 resize-none`,
    select: "flex-1 px-4 py-2.5 bg-white border border-gray-200 rounded-xl text-gray-900 text-sm focus:outline-none focus:border-gray-400 transition-colors",
    loginBtn: "w-full py-3.5 bg-gray-900 hover:bg-gray-800 text-white font-semibold rounded-xl transition-colors text-sm mt-1",
    submitReportBtn: "w-full py-4 bg-gray-900 hover:bg-gray-800 text-white font-semibold rounded-xl transition-colors text-sm",
    saveMaintBtn: "w-full py-4 bg-gray-900 hover:bg-gray-800 text-white font-semibold rounded-xl transition-colors text-sm mt-2",
    backDashBtn: "w-full py-3.5 bg-gray-900 hover:bg-gray-800 text-white font-semibold rounded-xl transition-colors text-sm",
    smallBtn: "flex items-center gap-2 px-4 py-2.5 bg-gray-900 hover:bg-gray-800 text-white rounded-xl text-sm font-medium transition-colors",
    cancelBtn: "px-5 py-3 bg-gray-100 hover:bg-gray-200 text-gray-600 rounded-xl text-sm transition-colors",
    saveUserBtn: "flex-1 py-3 bg-gray-900 hover:bg-gray-800 text-white rounded-xl text-sm font-semibold transition-colors",
    typeBtn: (active) =>
      `py-3 rounded-xl border text-sm font-semibold capitalize transition-colors ${active ? "bg-gray-900 border-gray-900 text-white" : "bg-white border-gray-200 text-gray-600 hover:border-gray-300"}`,
    urgBtn: (urgency, active) =>
      `py-3 rounded-xl border text-sm font-semibold capitalize transition-colors ${active ? "bg-gray-900 border-gray-900 text-white" : "bg-white border-gray-200 text-gray-600 hover:border-gray-300"}`,
    photoBtn: (active) =>
      `${active ? "bg-gray-50 border-gray-300 text-gray-700" : "bg-white border-gray-200 text-gray-500 hover:border-gray-300"} flex items-center gap-3 w-full px-4 py-3.5 rounded-xl border text-sm font-medium transition-colors`,
    photoIcon: "text-gray-400",
    checkIcon: "w-4 h-4 text-gray-600",
    confirmCircle: "bg-gray-100",
    confirmCheck: "w-10 h-10 text-gray-900",
    confirmTitle: "text-xl font-bold text-gray-900 mb-2",
    confirmText: "text-sm text-gray-500",
    summaryCard: "bg-white border border-gray-100 rounded-2xl p-4 shadow-sm",
    summaryLabel: "text-xs text-gray-400 uppercase tracking-wide font-medium mb-3",
    summaryCode: "text-sm font-bold text-gray-900",
    summaryType: "text-xs text-gray-500",
    summarySub: "text-xs text-gray-400 mt-0.5",
    alertIconBox: (status) => "w-9 h-9 rounded-xl bg-gray-100 flex items-center justify-center shrink-0",
    alertIcon: (status) => "w-4 h-4 text-gray-500",
    alertSub: (status) => "text-xs text-gray-400 mt-0.5",
    emptyCircle: "bg-gray-100",
    emptyCheck: "w-7 h-7 text-gray-600",
    emptyTitle: "text-sm font-semibold text-gray-700",
    emptySub: "text-sm text-gray-400 mt-1",
    totalLabel: "text-xs text-gray-400 font-medium",
    totalValue: "text-3xl font-bold text-gray-900 mt-1",
    totalSub: "text-xs text-gray-400 mt-1.5",
    chartTitle: "text-sm font-semibold text-gray-900 mb-4",
    detCode: "text-sm font-bold text-gray-900 w-14 shrink-0",
    detTrack: "h-1.5 bg-gray-100 rounded-full overflow-hidden",
    detFill: "h-full bg-gray-400 rounded-full",
    detCost: "text-sm text-gray-700 w-28 text-right shrink-0",
    addForm: "bg-white rounded-2xl border border-gray-200 shadow-sm p-5 space-y-3",
    formTitle: "text-sm font-semibold text-gray-900",
    userAvatar: "w-9 h-9 rounded-full bg-gray-100 flex items-center justify-center shrink-0",
    userAvatarTxt: "text-xs font-bold text-gray-600",
    userName: "text-sm font-semibold text-gray-900 truncate",
    userEmail: "text-xs text-gray-400 truncate",
    roleBadge: (role) =>
      `text-xs px-2.5 py-1 rounded-full font-medium shrink-0 ${
        role === "Administrador" ? "bg-purple-50 text-purple-700" :
        role === "Inspector de Material Mayor" ? "bg-blue-50 text-blue-700" :
        role === "Teniente Tercero" ? "bg-amber-50 text-amber-700" :
        "bg-gray-100 text-gray-600"
      }`,
    loginOuter: "min-h-full bg-gray-50 flex flex-col items-center justify-center p-6",
    loginGlow: "",
    loginLogoBox: "w-12 h-12 rounded-2xl bg-gray-900 flex items-center justify-center mx-auto mb-4",
    loginLogoIcon: "w-6 h-6 text-white",
    loginBrand1: "text-xs text-gray-400 font-medium uppercase tracking-wide",
    loginBrand2: "",
    loginTitle: "text-xl font-bold text-gray-900 mt-2",
    loginSub: "text-sm text-gray-500 mt-1",
    loginCard: "bg-white rounded-2xl border border-gray-100 shadow-sm p-6 space-y-4",
    loginFooter: "text-center text-xs text-gray-400 mt-6",
    note: "text-xs text-gray-400 text-center",
    bloginFooterLabel: "Acceso restringido · Uso interno",
    chart: {
      grid: "#f3f4f6",
      axis: "#9ca3af",
      bar: "#374151",
      barTop: "#374151",
      barLabel: "#6b7280",
      code: "#9ca3af",
      barOpacity: 0.8,
    },
  },
};

export function getChartColors(theme) {
  return themes[theme].chart;
}